---
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Create Zookeeper user
  user:
    name: zookeeper
    system: yes
    shell: /bin/false

- name: Download Zookeeper
  shell: curl -k -L -o /tmp/zookeeper.tar.gz https://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz
  args:
    creates: /tmp/zookeeper.tar.gz

- name: Extract Zookeeper
  unarchive:
    src: /tmp/zookeeper.tar.gz
    dest: /opt
    remote_src: yes
    creates: /opt/apache-zookeeper-{{ zookeeper_version }}-bin

- name: Create symlink
  file:
    src: /opt/apache-zookeeper-{{ zookeeper_version }}-bin
    dest: /opt/zookeeper
    state: link

- name: Create data directory
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
    owner: zookeeper
    group: zookeeper

- name: Create logs directory
  file:
    path: /opt/apache-zookeeper-{{ zookeeper_version }}-bin/logs
    state: directory
    owner: zookeeper
    group: zookeeper

- name: Set ownership
  file:
    path: /opt/apache-zookeeper-{{ zookeeper_version }}-bin
    owner: zookeeper
    group: zookeeper
    recurse: yes

- name: Create myid file
  copy:
    content: "{{ zk_id }}"
    dest: "{{ zookeeper_data_dir }}/myid"
    owner: zookeeper
    group: zookeeper

- name: Configure Zookeeper
  template:
    src: zoo.cfg.j2
    dest: /opt/zookeeper/conf/zoo.cfg
  notify: restart zookeeper

- name: Create systemd service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
  notify: restart zookeeper

- name: Start Zookeeper
  systemd:
    name: zookeeper
    state: started
    enabled: yes
    daemon_reload: yes
