---
sentinel_port: 26379
sentinel_master_name: "mymaster"
sentinel_master_host: "192.168.100.137"
sentinel_master_port: 6379
sentinel_quorum: 1
sentinel_down_after: 5000
sentinel_failover_timeout: 10000
sentinel_parallel_syncs: 1
redis_password: "redis123"
